<?php

namespace Database\Seeders;

use App\Models\QuizQuestion;
use Illuminate\Database\Seeder;

class LearningQuizQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $all = array_merge(
            $this->drivingQuestions(),
            $this->loksewhaQuestions(),
            $this->financeQuestions(),
            $this->rightsQuestions(),
            $this->competitiveQuestions(),
        );

        foreach ($all as $q) {
            QuizQuestion::updateOrCreate(
                ['category' => $q['category'], 'question' => $q['question']],
                $q
            );
        }

        $this->command->info('✅ LearningQuizQuestionSeeder: ' . count($all) . ' questions seeded.');
    }

    // ── Driving License ────────────────────────────────────────────────────
    private function drivingQuestions(): array
    {
        $c = 'driving_license';
        return [
            ['category'=>$c,'difficulty'=>'easy','question'=>'What is the speed limit in urban/city areas of Nepal?','question_np'=>'नेपालका शहरी क्षेत्रमा गति सीमा कति हो?','options'=>['40 km/h','60 km/h','80 km/h','30 km/h'],'options_np'=>['४० कि.मी./घन्टा','६० कि.मी./घन्टा','८० कि.मी./घन्टा','३० कि.मी./घन्टा'],'correct_index'=>0,'explanation'=>'Speed limit in urban areas of Nepal is 40 km/h.','explanation_np'=>'नेपालका शहरी क्षेत्रमा गति सीमा ४० कि.मी./घन्टा हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What color is a mandatory traffic sign?','question_np'=>'अनिवार्य ट्राफिक चिह्नको रंग कस्तो हुन्छ?','options'=>['Yellow','Blue','Red','Green'],'options_np'=>['पहेँलो','नीलो','रातो','हरियो'],'correct_index'=>2,'explanation'=>'Mandatory signs have a red circle/border.','explanation_np'=>'अनिवार्य चिह्नमा रातो गोलो/किनारा हुन्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'Which hand signal does a traffic police use to stop vehicles from the front?','question_np'=>'अगाडिबाट आउने सवारी रोक्न ट्राफिक प्रहरीले कुन इसारा गर्छ?','options'=>['Both arms extended sideways','Right arm raised upward','Circular arm motion','Left arm pointed forward'],'options_np'=>['दुवै हात दायाँ-बायाँ फैलाउने','दाहिने हात माथि उठाउने','हातको गोलो घुमाउने','बायाँ हात अगाडि देखाउने'],'correct_index'=>1,'explanation'=>'Right arm raised upward means stop for all approaching vehicles.','explanation_np'=>'दाहिने हात माथि उठाउनु भनेको सबैलाई रोक्नु हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'At what minimum age can a person obtain a Category A (motorcycle) license in Nepal?','question_np'=>'नेपालमा श्रेणी क (मोटरसाइकल) लाइसेन्स पाउने न्यूनतम उमेर कति हो?','options'=>['14 years','16 years','18 years','21 years'],'options_np'=>['१४ वर्ष','१६ वर्ष','१८ वर्ष','२१ वर्ष'],'correct_index'=>1,'explanation'=>'Minimum age for Category A motorcycle license is 16 years.','explanation_np'=>'श्रेणी क मोटरसाइकल लाइसेन्सको न्यूनतम उमेर १६ वर्ष हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'How long is a Nepal driving license valid before renewal?','question_np'=>'नेपाल ड्राइभिङ लाइसेन्स नवीकरण नगरी कति वर्ष वैध रहन्छ?','options'=>['2 years','3 years','5 years','10 years'],'options_np'=>['२ वर्ष','३ वर्ष','५ वर्ष','१० वर्ष'],'correct_index'=>2,'explanation'=>'Nepal driving license is valid for 5 years.','explanation_np'=>'नेपाल ड्राइभिङ लाइसेन्स ५ वर्षका लागि वैध हुन्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Which side should you overtake another vehicle in Nepal?','question_np'=>'नेपालमा अर्को सवारी ओभरटेक गर्दा कुन तर्फबाट गर्नुपर्छ?','options'=>['Left side','Right side','Either side','Only on highways'],'options_np'=>['बायाँ तर्फ','दाहिने तर्फ','जुनसुकै तर्फ','राजमार्गमा मात्र'],'correct_index'=>1,'explanation'=>'Overtaking must be done from the right side in Nepal.','explanation_np'=>'नेपालमा दाहिने तर्फबाट ओभरटेक गर्नुपर्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What shape are warning signs in Nepal?','question_np'=>'नेपालमा चेतावनी चिह्नको आकार कस्तो हुन्छ?','options'=>['Circle','Square','Triangle','Octagon'],'options_np'=>['गोलो','वर्गाकार','त्रिकोण','अष्टकोण'],'correct_index'=>2,'explanation'=>'Warning signs are triangular in shape.','explanation_np'=>'चेतावनी चिह्न त्रिकोण आकारको हुन्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'What is the highway speed limit for vehicles in Nepal?','question_np'=>'नेपालको राजमार्गमा सवारीको गति सीमा कति हो?','options'=>['60 km/h','70 km/h','80 km/h','100 km/h'],'options_np'=>['६० कि.मी./घन्टा','७० कि.मी./घन्टा','८० कि.मी./घन्टा','१०० कि.मी./घन्टा'],'correct_index'=>2,'explanation'=>'Highway speed limit in Nepal is 80 km/h.','explanation_np'=>'नेपालको राजमार्गमा गति सीमा ८० कि.मी./घन्टा हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'What does a yellow/orange triangular sign indicate?','question_np'=>'पहेँलो/सुन्तला त्रिकोण चिह्नले के जनाउँछ?','options'=>['Mandatory instruction','Warning/Hazard ahead','Information/Direction','Stop immediately'],'options_np'=>['अनिवार्य निर्देशन','सावधानी/खतरा अगाडि','सूचना/दिशा','तुरुन्त रोक्ने'],'correct_index'=>1,'explanation'=>'Yellow/orange triangular signs warn of hazards ahead.','explanation_np'=>'पहेँलो/सुन्तला त्रिकोण चिह्नले अगाडि खतरा रहेको चेतावनी दिन्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'Which emergency number should you call for an ambulance in Nepal?','question_np'=>'नेपालमा एम्बुलेन्सका लागि कुन नम्बरमा फोन गर्ने?','options'=>['100','101','102','103'],'options_np'=>['१००','१०१','१०२','१०३'],'correct_index'=>2,'explanation'=>'102 is the ambulance emergency number in Nepal.','explanation_np'=>'१०२ नेपालको एम्बुलेन्स आपतकालीन नम्बर हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Category B license in Nepal covers vehicles up to what weight?','question_np'=>'नेपालमा श्रेणी ख लाइसेन्सले कति केजी सम्मको सवारी चलाउन पाइन्छ?','options'=>['2000 kg','2500 kg','3000 kg','3500 kg'],'options_np'=>['२००० के.जी.','२५०० के.जी.','३००० के.जी.','३५०० के.जी.'],'correct_index'=>3,'explanation'=>'Category B covers light vehicles up to 3500 kg.','explanation_np'=>'श्रेणी ख ले ३५०० के.जी. सम्मको हलुका सवारी समेट्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'Where should warning triangles be placed when a vehicle breaks down?','question_np'=>'सवारी बिग्रिएमा चेतावनी त्रिकोण कहाँ राख्नुपर्छ?','options'=>['10m behind','25m behind','50m behind','100m behind'],'options_np'=>['१० मिटर पछाडि','२५ मिटर पछाडि','५० मिटर पछाडि','१०० मिटर पछाडि'],'correct_index'=>2,'explanation'=>'Warning triangles should be placed 50 meters behind the broken-down vehicle.','explanation_np'=>'बिग्रिएको सवारीभन्दा ५० मिटर पछाडि चेतावनी त्रिकोण राख्नुपर्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'Is wearing a seatbelt mandatory for the driver in Nepal?','question_np'=>'नेपालमा चालकले सिट बेल्ट लगाउनु अनिवार्य छ?','options'=>['Yes, mandatory','Only on highways','Only in cities','No, optional'],'options_np'=>['हो, अनिवार्य','राजमार्गमा मात्र','शहरमा मात्र','होइन, ऐच्छिक'],'correct_index'=>0,'explanation'=>'Seatbelt is mandatory for the driver and front passenger in Nepal.','explanation_np'=>'नेपालमा चालक र अगाडि बस्ने यात्रीलाई सिट बेल्ट अनिवार्य छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Overtaking is strictly prohibited near which location?','question_np'=>'कुन ठाउँ नजिक ओभरटेक कडाइसाथ निषेध गरिएको छ?','options'=>['Straight road','Traffic light','Bridge and blind corner','Downhill slope'],'options_np'=>['सिधो सडक','ट्राफिक बत्ती','पुल र अन्धो मोड','ओरालो बाटो'],'correct_index'=>2,'explanation'=>'Overtaking is prohibited on bridges, blind corners, and near intersections.','explanation_np'=>'पुल, अन्धो मोड र चोकनजिक ओभरटेक निषेध छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'After how many years of holding Category C license can someone get Category D?','question_np'=>'श्रेणी ग लाइसेन्स लिएको कति वर्षपछि श्रेणी घ लिन सकिन्छ?','options'=>['1 year','2 years','3 years','5 years'],'options_np'=>['१ वर्ष','२ वर्ष','३ वर्ष','५ वर्ष'],'correct_index'=>1,'explanation'=>'Must hold Category C license for 2 years before applying for Category D.','explanation_np'=>'श्रेणी घ अघि श्रेणी ग लाइसेन्स २ वर्ष राखेको हुनुपर्छ।','is_active'=>true],
        ];
    }

    // ── Loksewa ───────────────────────────────────────────────────────────
    private function loksewhaQuestions(): array
    {
        $c = 'loksewa';
        return [
            ['category'=>$c,'difficulty'=>'easy','question'=>'When was Nepal\'s Constitution 2072 promulgated?','question_np'=>'नेपाल संविधान २०७२ कहिले जारी भयो?','options'=>['2072 Ashwin 3','2072 Shrawan 1','2072 Chaitra 1','2072 Baisakh 15'],'options_np'=>['२०७२ असोज ३','२०७२ साउन १','२०७२ चैत्र १','२०७२ बैसाख १५'],'correct_index'=>0,'explanation'=>'Nepal Constitution 2072 was promulgated on Ashwin 3, 2072 BS (Sept 20, 2015).','explanation_np'=>'नेपाल संविधान २०७२ असोज ३, २०७२ मा जारी भयो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'How many provinces does Nepal have?','question_np'=>'नेपालमा कति वटा प्रदेश छन्?','options'=>['5','6','7','8'],'options_np'=>['५','६','७','८'],'correct_index'=>2,'explanation'=>'Nepal has 7 provinces under the federal structure.','explanation_np'=>'नेपालमा संघीय संरचना अन्तर्गत ७ प्रदेश छन्।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'How many members are in the House of Representatives (Pratinidhi Sabha)?','question_np'=>'प्रतिनिधि सभामा कति सदस्य हुन्छन्?','options'=>['205','240','275','330'],'options_np'=>['२०५','२४०','२७५','३३०'],'correct_index'=>2,'explanation'=>'The House of Representatives has 275 members (165 FPTP + 110 PR).','explanation_np'=>'प्रतिनिधि सभामा २७५ सदस्य हुन्छन् (१६५ FPTP + ११० PR)।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'Where is the headquarters of SAARC located?','question_np'=>'सार्कको मुख्यालय कहाँ अवस्थित छ?','options'=>['Delhi, India','Dhaka, Bangladesh','Kathmandu, Nepal','Colombo, Sri Lanka'],'options_np'=>['दिल्ली, भारत','ढाका, बंगलादेश','काठमाडौं, नेपाल','कोलम्बो, श्रीलंका'],'correct_index'=>2,'explanation'=>'SAARC headquarters is in Kathmandu, Nepal.','explanation_np'=>'सार्कको मुख्यालय काठमाडौं, नेपालमा छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Who unified Nepal in 1768?','question_np'=>'नेपाल एकीकरण १८२५ मा (सन् १७६८) कसले गरे?','options'=>['Rana Bahadur Shah','Prithvi Narayan Shah','Tribhuvan Shah','Jung Bahadur Rana'],'options_np'=>['राण बहादुर शाह','पृथ्वीनारायण शाह','त्रिभुवन शाह','जंगबहादुर राणा'],'correct_index'=>1,'explanation'=>'Prithvi Narayan Shah unified Nepal by conquering Kathmandu Valley in 1768.','explanation_np'=>'पृथ्वीनारायण शाहले सन् १७६८ मा काठमाडौं उपत्यका जितेर नेपाल एकीकरण गरे।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'What is the total area of Nepal?','question_np'=>'नेपालको कुल क्षेत्रफल कति हो?','options'=>['137,181 sq km','147,181 sq km','157,181 sq km','167,181 sq km'],'options_np'=>['१,३७,१८१ वर्ग कि.मी.','१,४७,१८१ वर्ग कि.मी.','१,५७,१८१ वर्ग कि.मी.','१,६७,१८१ वर्ग कि.मी.'],'correct_index'=>1,'explanation'=>'Nepal\'s total area is 147,181 square kilometers.','explanation_np'=>'नेपालको कुल क्षेत्रफल १,४७,१८१ वर्ग कि.मी. हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Which constitutional body conducts civil service examinations in Nepal?','question_np'=>'नेपालमा निजामती सेवा परीक्षा कुन संवैधानिक निकायले सञ्चालन गर्छ?','options'=>['CIAA','Election Commission','Public Service Commission','National Human Rights Commission'],'options_np'=>['अख्तियार दुरुपयोग अनुसन्धान आयोग','निर्वाचन आयोग','लोकसेवा आयोग','राष्ट्रिय मानव अधिकार आयोग'],'correct_index'=>2,'explanation'=>'Public Service Commission (Lok Sewa Aayog) conducts civil service exams.','explanation_np'=>'लोकसेवा आयोगले निजामती सेवा परीक्षा सञ्चालन गर्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What is the national bird of Nepal?','question_np'=>'नेपालको राष्ट्रिय पक्षी के हो?','options'=>['Peacock','Eagle','Danfe (Himalayan Monal)','Crane'],'options_np'=>['मयूर','चील','डाँफे','सारस'],'correct_index'=>2,'explanation'=>'Danfe (Himalayan Monal/Lophophorus) is the national bird of Nepal.','explanation_np'=>'डाँफे नेपालको राष्ट्रिय पक्षी हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'How many members does the National Assembly (Rastriya Sabha) have?','question_np'=>'राष्ट्रिय सभामा कति सदस्य हुन्छन्?','options'=>['40','50','59','75'],'options_np'=>['४०','५०','५९','७५'],'correct_index'=>2,'explanation'=>'The National Assembly has 59 members (56 elected + 3 nominated by President).','explanation_np'=>'राष्ट्रिय सभामा ५९ सदस्य हुन्छन् (५६ निर्वाचित + ३ राष्ट्रपतिद्वारा मनोनीत)।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'The highest peak in the world, Mt. Everest, has a height of?','question_np'=>'विश्वको सर्वोच्च शिखर सगरमाथाको उचाइ कति हो?','options'=>['8,756 m','8,848.86 m','8,900 m','8,611 m'],'options_np'=>['८,७५६ मिटर','८,८४८.८६ मिटर','८,९०० मिटर','८,६११ मिटर'],'correct_index'=>1,'explanation'=>'Mt. Everest height is 8,848.86 meters as surveyed in 2020.','explanation_np'=>'सन् २०२० को सर्वेक्षणअनुसार सगरमाथाको उचाइ ८,८४८.८६ मिटर हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What is the national flower of Nepal?','question_np'=>'नेपालको राष्ट्रिय फूल के हो?','options'=>['Lotus','Rose','Rhododendron (Lali Gurans)','Marigold'],'options_np'=>['कमल','गुलाब','लालीगुराँस','सयपत्री'],'correct_index'=>2,'explanation'=>'Rhododendron (Lali Gurans) is the national flower of Nepal.','explanation_np'=>'लालीगुराँस नेपालको राष्ट्रिय फूल हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Nepal became a Federal Democratic Republic in which year?','question_np'=>'नेपाल कहिले संघीय लोकतान्त्रिक गणतन्त्र बन्यो?','options'=>['2006','2007','2008','2009'],'options_np'=>['२०६३','२०६४','२०६५','२०६६'],'correct_index'=>2,'explanation'=>'Nepal was declared a Federal Democratic Republic on May 28, 2008 (Jeth 15, 2065 BS).','explanation_np'=>'नेपाल २०६५ जेठ १५ (सन् मे २८, २००८) मा संघीय लोकतान्त्रिक गणतन्त्र घोषित भयो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'How many local bodies (local governments) does Nepal have?','question_np'=>'नेपालमा कति वटा स्थानीय तह छन्?','options'=>['552','650','753','800'],'options_np'=>['५५२','६५०','७५३','८००'],'correct_index'=>2,'explanation'=>'Nepal has 753 local bodies: 6 metropolitan, 11 sub-metropolitan, 276 municipalities, 460 rural municipalities.','explanation_np'=>'नेपालमा ७५३ स्थानीय तह: ६ महानगर, ११ उपमहानगर, २७६ नगरपालिका, ४६० गाउँपालिका छन्।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What is Nepal\'s national sport?','question_np'=>'नेपालको राष्ट्रिय खेल के हो?','options'=>['Cricket','Football','Volleyball','Kabaddi'],'options_np'=>['क्रिकेट','फुटबल','भलिबल','कबड्डी'],'correct_index'=>2,'explanation'=>'Volleyball is the national sport of Nepal.','explanation_np'=>'भलिबल नेपालको राष्ट्रिय खेल हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Which article of the Nepal Constitution guarantees the right to education?','question_np'=>'नेपाल संविधानको कुन धाराले शिक्षाको हक सुनिश्चित गर्छ?','options'=>['Article 18','Article 25','Article 31','Article 35'],'options_np'=>['धारा १८','धारा २५','धारा ३१','धारा ३५'],'correct_index'=>2,'explanation'=>'Article 31 of Nepal Constitution guarantees the Right to Education.','explanation_np'=>'नेपाल संविधानको धारा ३१ ले शिक्षाको हक सुनिश्चित गर्छ।','is_active'=>true],
        ];
    }

    // ── Finance ───────────────────────────────────────────────────────────
    private function financeQuestions(): array
    {
        $c = 'finance';
        return [
            ['category'=>$c,'difficulty'=>'easy','question'=>'What does NRB stand for in Nepal?','question_np'=>'नेपालमा NRB को अर्थ के हो?','options'=>['National Revenue Board','Nepal Rastra Bank','Nepal Reserve Bureau','National Reserve Bank'],'options_np'=>['राष्ट्रिय राजस्व बोर्ड','नेपाल राष्ट्र बैंक','नेपाल रिजर्भ ब्युरो','राष्ट्रिय रिजर्भ बैंक'],'correct_index'=>1,'explanation'=>'NRB stands for Nepal Rastra Bank — the central bank of Nepal.','explanation_np'=>'NRB को अर्थ नेपाल राष्ट्र बैंक हो — नेपालको केन्द्रीय बैंक।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What is the standard VAT rate in Nepal?','question_np'=>'नेपालमा मूल्य अभिवृद्धि करको मानक दर कति हो?','options'=>['10%','13%','15%','18%'],'options_np'=>['१०%','१३%','१५%','१८%'],'correct_index'=>1,'explanation'=>'Standard VAT rate in Nepal is 13%.','explanation_np'=>'नेपालमा मूल्य अभिवृद्धि करको मानक दर १३% हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'What does NEPSE stand for?','question_np'=>'NEPSE को पूर्ण रूप के हो?','options'=>['Nepal Economic Policy Service Exchange','Nepal Stock Exchange','Nepal Enterprise Public Share Exchange','National Enterprise Promotion Stock Exchange'],'options_np'=>['नेपाल आर्थिक नीति सेवा विनिमय','नेपाल स्टक एक्सचेञ्ज','नेपाल उद्यम सार्वजनिक शेयर विनिमय','राष्ट्रिय उद्यम प्रवर्द्धन स्टक एक्सचेञ्ज'],'correct_index'=>1,'explanation'=>'NEPSE = Nepal Stock Exchange, established in 1994.','explanation_np'=>'NEPSE = Nepal Stock Exchange, १९९४ मा स्थापित।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'The Simple Interest formula is?','question_np'=>'साधारण ब्याजको सूत्र के हो?','options'=>['SI = P+R+T','SI = (P×R×T)/100','SI = P×R/T','SI = (P+T)/R'],'options_np'=>['SI = P+R+T','SI = (P×R×T)/100','SI = P×R/T','SI = (P+T)/R'],'correct_index'=>1,'explanation'=>'Simple Interest = (Principal × Rate × Time) / 100.','explanation_np'=>'साधारण ब्याज = (मूलधन × दर × समय) / १००।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'What type of bank account earns the highest interest in Nepal?','question_np'=>'नेपालमा कुन बैंक खातामा सबैभन्दा बढी ब्याज पाइन्छ?','options'=>['Current Account','Savings Account','Fixed Deposit Account','Call Deposit Account'],'options_np'=>['चालु खाता','बचत खाता','मुद्दती निक्षेप खाता','माग निक्षेप खाता'],'correct_index'=>2,'explanation'=>'Fixed Deposit (FD) accounts earn the highest interest rate.','explanation_np'=>'मुद्दती निक्षेप खातामा सबैभन्दा बढी ब्याज पाइन्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'Under Nepal income tax law (2080/81), what percentage of tax is paid on income above Rs. 20 lakh?','question_np'=>'नेपालको आयकर कानुन (२०८०/८१) अनुसार रु. २० लाखभन्दा माथिको आयमा कति प्रतिशत कर लाग्छ?','options'=>['20%','25%','30%','35%'],'options_np'=>['२०%','२५%','३०%','३५%'],'correct_index'=>2,'explanation'=>'Income above Rs. 20 lakh is taxed at 30%.','explanation_np'=>'रु. २० लाखभन्दा माथिको आयमा ३०% कर लाग्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What is PAN in Nepal taxation?','question_np'=>'नेपालको करमा PAN को अर्थ के हो?','options'=>['Public Account Number','Personal Access Number','Permanent Account Number','Payment Authorization Number'],'options_np'=>['सार्वजनिक खाता नम्बर','व्यक्तिगत पहुँच नम्बर','स्थायी लेखा नम्बर','भुक्तानी प्राधिकरण नम्बर'],'correct_index'=>2,'explanation'=>'PAN = Permanent Account Number. Mandatory for all taxpayers in Nepal.','explanation_np'=>'PAN = स्थायी लेखा नम्बर। नेपालका सबै करदाताका लागि अनिवार्य।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Which class of bank is a commercial bank in Nepal\'s NRB classification?','question_np'=>'नेरास वर्गीकरणमा वाणिज्य बैंक कुन वर्गमा पर्छ?','options'=>['Class A','Class B','Class C','Class D'],'options_np'=>['वर्ग क','वर्ग ख','वर्ग ग','वर्ग घ'],'correct_index'=>0,'explanation'=>'Commercial banks are classified as Class A banks by Nepal Rastra Bank.','explanation_np'=>'नेपाल राष्ट्र बैंकले वाणिज्य बैंकलाई वर्ग क मा वर्गीकरण गर्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'What is the 50-30-20 budgeting rule?','question_np'=>'५०-३०-२० बजेट नियम के हो?','options'=>['50% savings, 30% needs, 20% wants','50% needs, 30% wants, 20% savings','50% tax, 30% needs, 20% savings','50% investments, 30% bills, 20% food'],'options_np'=>['५०% बचत, ३०% आवश्यकता, २०% इच्छा','५०% आवश्यकता, ३०% इच्छा, २०% बचत','५०% कर, ३०% आवश्यकता, २०% बचत','५०% लगानी, ३०% बिल, २०% खाना'],'correct_index'=>1,'explanation'=>'50% of income for needs, 30% for wants, 20% for savings/investments.','explanation_np'=>'आयको ५०% आवश्यकताका लागि, ३०% इच्छाका लागि, २०% बचत/लगानीका लागि।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'Which organization regulates insurance companies in Nepal?','question_np'=>'नेपालमा बीमा कम्पनीहरूलाई कुन संस्थाले नियमन गर्छ?','options'=>['NRB','SEBON','IRAN (Insurance Regulatory Authority)','Ministry of Finance'],'options_np'=>['नेपाल राष्ट्र बैंक','धितोपत्र बोर्ड','बीमा नियमन प्राधिकरण','अर्थ मन्त्रालय'],'correct_index'=>2,'explanation'=>'IRAN (Insurance Regulatory Authority of Nepal) regulates all insurance companies.','explanation_np'=>'बीमा नियमन प्राधिकरण (IRAN) ले सबै बीमा कम्पनीहरूलाई नियमन गर्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'What is the minimum capital requirement for commercial banks in Nepal?','question_np'=>'नेपालमा वाणिज्य बैंकका लागि न्यूनतम पुँजी आवश्यकता कति छ?','options'=>['Rs. 4 billion','Rs. 6 billion','Rs. 8 billion','Rs. 10 billion'],'options_np'=>['रु. ४ अर्ब','रु. ६ अर्ब','रु. ८ अर्ब','रु. १० अर्ब'],'correct_index'=>2,'explanation'=>'Minimum paid-up capital for commercial banks in Nepal is Rs. 8 billion.','explanation_np'=>'नेपालमा वाणिज्य बैंकको न्यूनतम चुक्ता पुँजी रु. ८ अर्ब हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'SEBON regulates which sector in Nepal?','question_np'=>'नेपालमा SEBON ले कुन क्षेत्रलाई नियमन गर्छ?','options'=>['Banking sector','Insurance sector','Securities/Stock market','Foreign exchange'],'options_np'=>['बैंकिङ क्षेत्र','बीमा क्षेत्र','धितोपत्र/शेयर बजार','विदेशी विनिमय'],'correct_index'=>2,'explanation'=>'SEBON (Securities Board of Nepal) regulates the stock market and securities.','explanation_np'=>'धितोपत्र बोर्ड नेपाल (SEBON) ले शेयर बजार र धितोपत्रलाई नियमन गर्छ।','is_active'=>true],
        ];
    }

    // ── Rights & Law ──────────────────────────────────────────────────────
    private function rightsQuestions(): array
    {
        $c = 'rights';
        return [
            ['category'=>$c,'difficulty'=>'easy','question'=>'How many fundamental rights does Nepal Constitution 2072 guarantee?','question_np'=>'नेपाल संविधान २०७२ ले कति वटा मौलिक हक सुनिश्चित गर्छ?','options'=>['20','25','31','40'],'options_np'=>['२०','२५','३१','४०'],'correct_index'=>2,'explanation'=>'Nepal Constitution 2072 guarantees 31 fundamental rights in Part 3 (Articles 16-46).','explanation_np'=>'नेपाल संविधान २०७२ को भाग ३ (धारा १६-४६) मा ३१ मौलिक हक सुनिश्चित छन्।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What is the maximum working hours per day under Nepal Labor Act 2074?','question_np'=>'श्रम ऐन २०७४ अन्तर्गत दैनिक अधिकतम काम घण्टा कति हो?','options'=>['6 hours','8 hours','10 hours','12 hours'],'options_np'=>['६ घण्टा','८ घण्टा','१० घण्टा','१२ घण्टा'],'correct_index'=>1,'explanation'=>'Maximum 8 hours per day and 48 hours per week under Labor Act 2074.','explanation_np'=>'श्रम ऐन २०७४ अनुसार दैनिक अधिकतम ८ घण्टा र साप्ताहिक ४८ घण्टा।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'How many weeks of maternity leave is a worker entitled to under Nepal Labor Act 2074?','question_np'=>'श्रम ऐन २०७४ अनुसार प्रसूति बिदा कति हप्ता पाइन्छ?','options'=>['8 weeks','10 weeks','12 weeks','14 weeks'],'options_np'=>['८ हप्ता','१० हप्ता','१२ हप्ता','१४ हप्ता'],'correct_index'=>3,'explanation'=>'Maternity leave is 14 weeks (98 days) under Nepal Labor Act 2074.','explanation_np'=>'श्रम ऐन २०७४ अनुसार प्रसूति बिदा १४ हप्ता (९८ दिन) हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What is the minimum monthly wage for unskilled workers in Nepal (as of 2080 BS)?','question_np'=>'नेपालमा अदक्ष श्रमिकको न्यूनतम मासिक ज्याला (२०८० बाट) कति हो?','options'=>['Rs. 10,000','Rs. 12,000','Rs. 15,000','Rs. 18,000'],'options_np'=>['रु. १०,०००','रु. १२,०००','रु. १५,०००','रु. १८,०००'],'correct_index'=>2,'explanation'=>'Minimum monthly wage for unskilled workers is Rs. 15,000 (as of 2080 BS).','explanation_np'=>'२०८० बाट अदक्ष श्रमिकको न्यूनतम मासिक ज्याला रु. १५,००० हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Which article of Nepal Constitution deals with Right to Equality?','question_np'=>'नेपाल संविधानको कुन धारामा समानताको हक उल्लेख छ?','options'=>['Article 16','Article 17','Article 18','Article 19'],'options_np'=>['धारा १६','धारा १७','धारा १८','धारा १९'],'correct_index'=>2,'explanation'=>'Article 18 of Nepal Constitution guarantees the Right to Equality.','explanation_np'=>'नेपाल संविधानको धारा १८ ले समानताको हक सुनिश्चित गर्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'What health coverage does the Nepal government provide to citizens under health insurance?','question_np'=>'स्वास्थ्य बीमामा नेपाल सरकारले नागरिकलाई कति रुपैयाँको कभरेज दिन्छ?','options'=>['Rs. 1 lakh','Rs. 3 lakh','Rs. 5 lakh','Rs. 10 lakh'],'options_np'=>['रु. १ लाख','रु. ३ लाख','रु. ५ लाख','रु. १० लाख'],'correct_index'=>2,'explanation'=>'Nepal government provides Rs. 5 lakh health coverage per year per family under health insurance scheme.','explanation_np'=>'नेपाल सरकारले स्वास्थ्य बीमा योजनामा परिवारलाई वार्षिक रु. ५ लाखको कभरेज दिन्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'How many days of sick leave is a worker entitled to per year under Nepal Labor Act 2074?','question_np'=>'श्रम ऐन २०७४ अनुसार श्रमिकले वर्षमा कति दिन बिरामी बिदा पाउँछ?','options'=>['7 days','10 days','12 days','15 days'],'options_np'=>['७ दिन','१० दिन','१२ दिन','१५ दिन'],'correct_index'=>2,'explanation'=>'Workers are entitled to 12 days of sick leave per year.','explanation_np'=>'श्रमिकले वर्षमा १२ दिन बिरामी बिदा पाउँछ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'Which law protects consumers from unfair trade practices in Nepal?','question_np'=>'नेपालमा कुन कानुनले उपभोक्तालाई अनुचित व्यापारिक अभ्यासबाट संरक्षण गर्छ?','options'=>['Labor Act 2074','Consumer Protection Act 2075','Civil Code 2074','Competition Act 2063'],'options_np'=>['श्रम ऐन २०७४','उपभोक्ता संरक्षण ऐन २०७५','मुलुकी देवानी संहिता २०७४','प्रतिस्पर्धा ऐन २०६३'],'correct_index'=>1,'explanation'=>'Consumer Protection Act 2075 protects consumers from unfair trade practices.','explanation_np'=>'उपभोक्ता संरक्षण ऐन २०७५ ले उपभोक्तालाई अनुचित व्यापारिक अभ्यासबाट संरक्षण गर्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'How many days of paternity leave does Nepal Labor Act 2074 provide?','question_np'=>'श्रम ऐन २०७४ ले बाबु बिदा कति दिन प्रदान गर्छ?','options'=>['7 days','10 days','15 days','20 days'],'options_np'=>['७ दिन','१० दिन','१५ दिन','२० दिन'],'correct_index'=>2,'explanation'=>'Nepal Labor Act 2074 provides 15 days of paternity leave.','explanation_np'=>'श्रम ऐन २०७४ ले बाबु बिदा १५ दिन प्रदान गर्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'Overtime pay must be at least what rate compared to normal pay under Nepal Labor Act?','question_np'=>'श्रम ऐन अनुसार ओभरटाइम पारिश्रमिक सामान्य पारिश्रमिकको कति गुणा हुनुपर्छ?','options'=>['1.25x','1.5x','2x','2.5x'],'options_np'=>['१.२५ गुणा','१.५ गुणा','२ गुणा','२.५ गुणा'],'correct_index'=>1,'explanation'=>'Overtime must be paid at 1.5 times the regular rate.','explanation_np'=>'ओभरटाइम सामान्य दरको १.५ गुणामा भुक्तानी गर्नुपर्छ।','is_active'=>true],
        ];
    }

    // ── Competitive ───────────────────────────────────────────────────────
    private function competitiveQuestions(): array
    {
        $c = 'competitive';
        return [
            ['category'=>$c,'difficulty'=>'easy','question'=>'What does BFIA stand for in Nepal?','question_np'=>'नेपालमा BFIA को अर्थ के हो?','options'=>['Bank and Financial Institution Act','Budget and Finance Investment Act','Banking Facility and Insurance Act','Business Finance Institution Authority'],'options_np'=>['बैंक तथा वित्तीय संस्था ऐन','बजेट र वित्त लगानी ऐन','बैंकिङ सुविधा र बीमा ऐन','व्यापार वित्त संस्था प्राधिकरण'],'correct_index'=>0,'explanation'=>'BFIA = Bank and Financial Institutions Act 2073 — the main banking law in Nepal.','explanation_np'=>'BFIA = बैंक तथा वित्तीय संस्था ऐन २०७३ — नेपालको मुख्य बैंकिङ कानुन।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'What is the minimum age requirement for Nepal Army Sainya (Private) recruitment?','question_np'=>'नेपाली सेना सैनिक भर्तीको न्यूनतम उमेर सीमा कति हो?','options'=>['16 years','18 years','20 years','21 years'],'options_np'=>['१६ वर्ष','१८ वर्ष','२० वर्ष','२१ वर्ष'],'correct_index'=>1,'explanation'=>'Minimum age for Nepal Army Sainya recruitment is 18 years.','explanation_np'=>'नेपाली सेना सैनिक भर्तीको न्यूनतम उमेर १८ वर्ष हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What educational qualification is required to become a Nepal Police Constable?','question_np'=>'नेपाल प्रहरी जवान हुन कुन शैक्षिक योग्यता चाहिन्छ?','options'=>['Class 8 pass','SLC/SEE pass','Intermediate (10+2)','Bachelor\'s degree'],'options_np'=>['कक्षा ८ उत्तीर्ण','एसईई उत्तीर्ण','इन्टरमिडिएट (१०+२)','स्नातक'],'correct_index'=>1,'explanation'=>'SLC/SEE pass is required for Nepal Police Constable position.','explanation_np'=>'नेपाल प्रहरी जवान हुन एसईई उत्तीर्ण चाहिन्छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'The Teaching Service Commission exam has how many papers for secondary level?','question_np'=>'माध्यमिक तहका लागि शिक्षक सेवा आयोगको परीक्षामा कति पेपर हुन्छ?','options'=>['1 paper','2 papers','3 papers','4 papers'],'options_np'=>['१ पेपर','२ पेपर','३ पेपर','४ पेपर'],'correct_index'=>1,'explanation'=>'TSC has 2 papers: Paper 1 (Subject Knowledge) and Paper 2 (Teaching Methodology + Education Law).','explanation_np'=>'शिक्षक सेवा आयोगमा २ पेपर हुन्छ: पेपर १ (विषय ज्ञान) र पेपर २ (शिक्षण विधि + शिक्षा कानुन)।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'What is the single borrower limit for commercial banks in Nepal?','question_np'=>'नेपालमा वाणिज्य बैंकका लागि एकल ऋणी सीमा कति प्रतिशत हो?','options'=>['15% of core capital','20% of core capital','25% of core capital','30% of core capital'],'options_np'=>['मूल पुँजीको १५%','मूल पुँजीको २०%','मूल पुँजीको २५%','मूल पुँजीको ३०%'],'correct_index'=>2,'explanation'=>'Single borrower limit is 25% of core capital for commercial banks.','explanation_np'=>'वाणिज्य बैंकको एकल ऋणी सीमा मूल पुँजीको २५% हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'What does CRR stand for in banking?','question_np'=>'बैंकिङमा CRR को अर्थ के हो?','options'=>['Current Reserve Ratio','Cash Reserve Ratio','Credit Risk Rating','Central Rate Requirement'],'options_np'=>['चालु आरक्षित अनुपात','नगद आरक्षण अनुपात','ऋण जोखिम मूल्यांकन','केन्द्रीय दर आवश्यकता'],'correct_index'=>1,'explanation'=>'CRR = Cash Reserve Ratio. The percentage of deposits banks must keep with the central bank.','explanation_np'=>'CRR = नगद आरक्षण अनुपात। बैंकले केन्द्रीय बैंकमा राख्नुपर्ने निक्षेपको प्रतिशत।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'How many years of experience is required to teach at Higher Secondary level in Nepal?','question_np'=>'नेपालमा उच्च माध्यमिक तहमा पढाउन कुन शैक्षिक योग्यता चाहिन्छ?','options'=>['Bachelor\'s degree','Master\'s degree','PhD','Intermediate'],'options_np'=>['स्नातक','स्नातकोत्तर','पिएचडी','इन्टरमिडिएट'],'correct_index'=>1,'explanation'=>'Master\'s degree is required to teach at Higher Secondary level.','explanation_np'=>'उच्च माध्यमिक तहमा पढाउन स्नातकोत्तर योग्यता आवश्यक छ।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'easy','question'=>'Nepal Police emergency number is?','question_np'=>'नेपाल प्रहरीको आपतकालीन नम्बर के हो?','options'=>['101','100','102','199'],'options_np'=>['१०१','१००','१०२','१९९'],'correct_index'=>1,'explanation'=>'100 is Nepal Police emergency number.','explanation_np'=>'१०० नेपाल प्रहरीको आपतकालीन नम्बर हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'hard','question'=>'What is the maximum age limit for Nepal Army Sainya (Private) recruitment?','question_np'=>'नेपाली सेना सैनिक भर्तीको अधिकतम उमेर सीमा कति हो?','options'=>['22 years','25 years','28 years','30 years'],'options_np'=>['२२ वर्ष','२५ वर्ष','२८ वर्ष','३० वर्ष'],'correct_index'=>1,'explanation'=>'Maximum age for Nepal Army Sainya is 25 years.','explanation_np'=>'नेपाली सेना सैनिकको अधिकतम उमेर २५ वर्ष हो।','is_active'=>true],
            ['category'=>$c,'difficulty'=>'medium','question'=>'SAARC was founded in which year?','question_np'=>'सार्क कुन वर्ष स्थापना भयो?','options'=>['1980','1983','1985','1988'],'options_np'=>['१९८०','१९८३','१९८५','१९८८'],'correct_index'=>2,'explanation'=>'SAARC was founded on December 8, 1985 in Dhaka, Bangladesh.','explanation_np'=>'सार्क सन् १९८५ डिसेम्बर ८ मा ढाका, बंगलादेशमा स्थापित भयो।','is_active'=>true],
        ];
    }
}
